In [15]:
#Write a NumPy program to create an element-wise comparison (greater,
#greater_equal, less and less_equal) of two given arrays.
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x,y))   
print(np.greater_equal(x,y))
print(np.greater(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[ True  True  True  True  True  True  True  True  True False]
[ True  True  True  True  True  True  True  True  True False]
[False False False False False False False False False False]
[False False False False False False False False False  True]
[ True  True  True  True  True  True  True  True  True  True]


In [18]:
#Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
print(np.zeros(10))
print(np.ones(10))
print(np.full(10,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [22]:
#Write a NumPy program to generate a random number between 0 and 1
print(np.random.random())

0.5968318987244735


In [27]:
#Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
print(np.arange(10,22).reshape(3,4))


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [31]:
#Write a NumPy program to convert an array to a float type.
#Sample output:
Original_array=np.array([1, 2, 3, 4])
print(Original_array.astype(int))


[1 2 3 4]


In [32]:
#Write a NumPy program to convert a list and tuple into arrays
list=[1,2,2,3,4,5,6]
tuple1=(1,2,5,8,9,8)
print(np.array(list))
print()
print(np.array(tuple1))

[1 2 2 3 4 5 6]
[1 2 5 8 9 8]


In [35]:
#Write a NumPy program to find common values between two arrays. 
Array1=np.array([ 0,10,20,40,60])
Array2=np.array([10, 30, 40])
print(np.intersect1d(Array1,Array2))
    

[10 40]


In [38]:
#Write a NumPy program to find the indices of the maximum and minimum
#values along the given axis of an array. 
#Original array: [1 2 3 4 5 6]
x=np.array([1,2,3,4,5,6])
print(np.argmax(x))
print(np.argmin(x))


5
0


In [43]:
#Write a NumPy program to compute the determinant of a given square
#array.
x=[[1,2],
   [3,4]]
a=np.array(x)
print(np.linalg.det(a))

-2.0000000000000004


In [48]:
#Write a NumPy program to compute the multiplication of two given
#matrixes.
a=np.array([[1,2],[4,5],[1,2]])
b=np.array([[1,2],[3,4],[1,2]])
print(np.multiply(a,b))


[[ 1  4]
 [12 20]
 [ 1  4]]


In [56]:
#Write a NumPy program to create a structured array from given
#student name, height, class and their data types. Now sort the array on
#height. 
#Original array:
#[('James', 5, 48.5 ) ('Nail', 6, 52.5 ) ('Paul', 5, 42.1 )
#(Pit, 5, 40.11)]
data_type=[('names','S15'),('class',int),('height',float)]
Student_details=[('James',5,48.5),('Nail',6,52.5),('Paul',5,42.1),('Pit',5,40.11)]
Student=np.array(Student_details,dtype=data_type)
print(Student)
print(np.sort(Student,order='height'))

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [57]:
#Write a NumPy program to get the indices of the sorted elements of
#a given array. 
#Original array:
#[1023 5202 6230 1671 1682 5241 4532]
x=np.array([1023,5202,6230,1671,1682,5241,4532])
print(np.argsort(x))




[0 3 4 6 1 5 2]


In [65]:
#Write a NumPy program to concatenate element-wise two arrays of
#string. 
#Array1:
#['Python', 'PHP']
#Array2:
#['Java' ,'C++']
a=np.array(['Python','Php'])
b=np.array(['Java','C++'])
print(a)
print(b)
print(np.concatenate((a,b)))

['Python' 'Php']
['Java' 'C++']
['Python' 'Php' 'Java' 'C++']


In [68]:
#Write a NumPy program to repeat all the elements three times of a
#given array of string 
#Expected Output:
#Original Array:
#[Python PHP Java C++]
x=np.array(['Python','PHP','Java','C++'],dtype='str')
print(x)
print(np.char.multiply(x,3))

['Python' 'PHP' 'Java' 'C++']
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


In [72]:
#Write a NumPy program to split the element of a given array with
#spaces. 
#Original Array:
#[Python PHP Java C++]
x=np.array(['Python PHP Java C++'],dtype='str')
print(x)
print(np.char.split(x))

['Python PHP Java C++']
[list(['Python', 'PHP', 'Java', 'C++'])]
